import { beforeEach, describe, expect, it, vi } from 'vitest';
import worker from '../cloudflare-unified-worker';

class FakeD1 {
  usage = new Map<string, number>();
  trial = new Map<string, number>();

  prepare(sql: string) {
    return {
      bind: (...args: string[]) => ({
        run: async () => this.run(sql, args),
        first: async () => this.first(sql, args),
      }),
    };
  }

  private run(sql: string, args: string[]) {
    if (sql.includes('INSERT INTO usage')) {
      const key = `${args[0]}:${args[1]}`;
      const current = this.usage.get(key) || 0;
      const cap = Number(args[2]);
      if (current >= cap) return { meta: { changes: 0 } };
      this.usage.set(key, current + 1);
      return { meta: { changes: 1 } };
    }
    if (sql.includes('INSERT INTO trial_sessions')) {
      const [userId, sessionId] = args;
      const key = `${userId}:${sessionId}`;
      const current = this.trial.get(key);
      if (current !== undefined) {
        if (current >= 12) return { meta: { changes: 0 } };
        this.trial.set(key, current + 1);
        return { meta: { changes: 1 } };
      }
      const sessions = [...this.trial.keys()].filter((value) => value.startsWith(`${userId}:`)).length;
      if (sessions >= 3) return { meta: { changes: 0 } };
      this.trial.set(key, 1);
      return { meta: { changes: 1 } };
    }
    if (sql.includes('UPDATE usage')) {
      const key = `${args[0]}:${args[1]}`;
      this.usage.set(key, Math.max(0, (this.usage.get(key) || 0) - 1));
      return { meta: { changes: 1 } };
    }
    if (sql.includes('UPDATE trial_sessions')) {
      const key = `${args[0]}:${args[1]}`;
      if (this.trial.has(key)) this.trial.set(key, Math.max(0, (this.trial.get(key) || 0) - 1));
      return { meta: { changes: 1 } };
    }
    if (sql.includes('DELETE FROM trial_sessions')) {
      const key = `${args[0]}:${args[1]}`;
      if ((this.trial.get(key) || 0) <= 0) this.trial.delete(key);
      return { meta: { changes: 1 } };
    }
    return { meta: { changes: 0 } };
  }

  private first(sql: string, args: string[]) {
    if (sql.includes('SELECT turns FROM trial_sessions')) {
      const value = this.trial.get(`${args[0]}:${args[1]}`);
      return value === undefined ? null : { turns: value };
    }
    if (sql.includes('SELECT COUNT(*) AS used')) {
      const count = [...this.trial.keys()].filter((value) => value.startsWith(`${args[0]}:`)).length;
      return { used: count };
    }
    return null;
  }
}

class FakeKv {
  values = new Map<string, string>();
  async get(key: string) { return this.values.get(key) || null; }
}

describe('Worker quota accounting through HTTP handlers', () => {
  const sessionSecret = 'quota-test-session-secret';
  let mode: 'success' | 'failure' = 'success';
  let sessionToken = '';
  let env: Record<string, unknown>;

  beforeEach(async () => {
    const d1 = new FakeD1();
    const redeemed = new FakeKv();
    mode = 'success';
    env = {
      GOOGLE_CLIENT_ID: 'client-id',
      SESSION_SECRET: sessionSecret,
      GEMINI_API_KEY: 'test-key',
      AI_RATE_LIMIT_PER_MINUTE: '100',
      AI_RATE_LIMIT_PER_DAY: '100',
      DB: d1,
      REDEEMED_CODES: redeemed,
    };
    vi.stubGlobal('fetch', async (url: string) => {
      if (url.includes('googleapis.com/oauth2/v3/certs')) {
        return new Response(JSON.stringify({ keys: [] }), { status: 200 });
      }
      if (url.includes('generativelanguage.googleapis.com')) {
        if (mode === 'failure') return new Response('failed', { status: 500 });
        return new Response(JSON.stringify({
          candidates: [{ content: { parts: [{ text: '{"reply_de":"Hallo","reply_ar":"مرحباً","is_correct":true}' }] } }],
        }), { status: 200 });
      }
      return new Response('not found', { status: 404 });
    });
    // The session token is generated by the real handler in the auth tests.
    sessionToken = '';
  });

  async function issueSession() {
    const encode = (value: unknown) => Buffer.from(JSON.stringify(value)).toString('base64url');
    const header = encode({ alg: 'HS256', typ: 'JWT' });
    const payload = encode({ sub: 'quota-user', email: 'quota@example.com', aud: 'katzu', exp: Math.floor(Date.now() / 1000) + 3600 });
    const key = await crypto.subtle.importKey(
      'raw',
      new TextEncoder().encode(sessionSecret),
      { name: 'HMAC', hash: 'SHA-256' },
      false,
      ['sign'],
    );
    const signature = await crypto.subtle.sign('HMAC', key, new TextEncoder().encode(`${header}.${payload}`));
    sessionToken = `${header}.${payload}.${Buffer.from(signature).toString('base64url')}`;
  }

  async function turn(sessionId: string, overrides: Record<string, unknown> = {}) {
    return worker.fetch(new Request('https://worker.test/ai/turn', {
      method: 'POST',
      headers: { Authorization: `Bearer ${sessionToken}`, 'Content-Type': 'application/json' },
      body: JSON.stringify({
        user_message: 'Hallo',
        scenario_id: 'test',
        scenario_title: 'Test',
        cefr_level: 'A1',
        session_id: sessionId,
        ...overrides,
      }),
    }), env);
  }

  it('fails closed when D1 is missing', async () => {
    await issueSession();
    env.DB = undefined;
    expect((await turn('missing-db')).status).toBe(503);
  });

  it('allows exactly FREE_SESSIONS fresh free sessions under parallel load', async () => {
    await issueSession();
    const responses = await Promise.all(
      Array.from({ length: 20 }, (_, index) => turn(`fresh-${index}`)),
    );
    expect(responses.filter((response) => response.status === 200)).toHaveLength(3);
    expect(responses.filter((response) => response.status === 402 || response.status === 429)).toHaveLength(17);
    expect((env.DB as FakeD1).trial.size).toBe(3);
  });

  it('allows 12 parallel turns in one free session and consumes one session', async () => {
    await issueSession();
    const responses = await Promise.all(
      Array.from({ length: 20 }, () => turn('one-session')),
    );
    expect(responses.filter((response) => response.status === 200)).toHaveLength(12);
    expect(responses.filter((response) => response.status === 429)).toHaveLength(8);
    expect((env.DB as FakeD1).trial.size).toBe(1);
    expect((env.DB as FakeD1).trial.get('quota-user:one-session')).toBe(12);
  });

  it('does not count translation or hints as usage or trial turns', async () => {
    await issueSession();
    const headers = { Authorization: `Bearer ${sessionToken}`, 'Content-Type': 'application/json' };
    const before = JSON.stringify({ usage: [...(env.DB as FakeD1).usage], trial: [...(env.DB as FakeD1).trial] });
    await worker.fetch(new Request('https://worker.test/ai/translate', {
      method: 'POST', headers, body: JSON.stringify({ text: 'Hallo' }),
    }), env);
    await worker.fetch(new Request('https://worker.test/ai/hints', {
      method: 'POST', headers, body: JSON.stringify({ last_ai_reply: 'Hallo', cefr_level: 'A1' }),
    }), env);
    expect(JSON.stringify({ usage: [...(env.DB as FakeD1).usage], trial: [...(env.DB as FakeD1).trial] })).toBe(before);
  });

  it('does not create trial rows for subscribers and enforces only the daily cap', async () => {
    await issueSession();
    (env.REDEEMED_CODES as FakeKv).values.set('account:quota-user', JSON.stringify({
      expiresAt: new Date(Date.now() + 86400000).toISOString(),
    }));
    env.AI_DAILY_TURN_CAP = '2';
    const responses = await Promise.all(
      Array.from({ length: 5 }, (_, index) => turn(`subscriber-${index}`)),
    );
    expect(responses.filter((response) => response.status === 200)).toHaveLength(2);
    expect((env.DB as FakeD1).trial.size).toBe(0);
    expect((env.DB as FakeD1).usage.get(`quota-user:${new Date().toISOString().slice(0, 10)}`)).toBe(2);
  });

  it('refunds the first trial turn and daily usage after Gemini fails', async () => {
    await issueSession();
    mode = 'failure';
    const response = await turn('failed-first');
    expect(response.status).toBe(502);
    expect((env.DB as FakeD1).trial.has('quota-user:failed-first')).toBe(false);
    expect((env.DB as FakeD1).usage.get(`quota-user:${new Date().toISOString().slice(0, 10)}`)).toBe(0);
  });
});
